### ISSUE TITLE
vitalium-verb link leads to OctaSine url

### ISSUE THREAD

**Issue by marceliq** [RustoMCSpit/awesome-linux-clap-list#1]
Hi,

just noticed that vitalium-verb link leads to OctaSine.

btw, thanks for plugin list.

m

**Comment by RustoMCSpit** [comment]
> Hi,
> 
> just noticed that vitalium-verb link leads to OctaSine.
> 
> btw, thanks for plugin list.
> 
> m

will fix later thanks

also dont worry about it, i wish i had this list instead of doing hours of searching

**Comment by RustoMCSpit** [comment]
fixed
