### ISSUE TITLE
godot-clap

### ISSUE THREAD

**Issue by yankscally** [RustoMCSpit/awesome-linux-clap-list#2]
hey - add me on discord! would love to chat about this.

@yankscally

**Comment by RustoMCSpit** [comment]
> hey - add me on discord! would love to chat about this.
> 
> @yankscally

sent but ive no idea why we cant talk here, is this about me wanting to have godot be able to produce .clap exports

**Comment by RustoMCSpit** [comment]
@yankscally are you still interested in this?
